version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:55"
    timezone: "America/Chicago"
  - dependency-name: bootstrap
    versions:
    - 5.3.1
